### ISSUE TITLE
Invalid Character Token 

### ISSUE THREAD

**Issue by arwaniall86** [maksim-paskal/hcloud-k8s-ctl#116]
Hello maksim 

INFO[0000]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:49 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.NewApplicationAPI() Connecting to Hetzner Cloud API...
INFO[0000]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:65 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).validateConfig() Validating config...
FATA[0000]github.com/maksim-paskal/hcloud-k8s-ctl/cmd/main.go:76 main.main() hcloudClient.Location.Get: Authorization token contains invalid characters

Thank You

**Comment by maksim-paskal** [comment]
Hi, it seems that token you use have some not acceptable symbols.

Try to delete `.hcloudauth` file, and set this token with env

```bash
export HCLOUD_TOKEN=your-hcloud-token


```

**Comment by maksim-paskal** [comment]
I reproduce this error only when `.hcloudauth` have empty lines. Try make this file only with one line.
