### ISSUE TITLE
Error creating LoadBalancer

### ISSUE THREAD

**Issue by ramses3** [maksim-paskal/hcloud-k8s-ctl#63]
Hello, is this something can be solved on configuration ?
> INFO[0000]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:43 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.NewApplicationAPI() Connecting to Hetzner Cloud API...           
> INFO[0000]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:59 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).validateConfig() Validating config...                         
> INFO[0000]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:574 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).NewCluster() Creating cluster...                          
> INFO[0000]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:537 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).createNetwork() Creating network...                          
> INFO[0001]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:992 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).CreateFirewall() Creating firewall...                         
> INFO[0001]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:518 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).createSSHKey() Creating sshKey...                           
> INFO[0001]github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api/api.go:352 github.com/maksim-paskal/hcloud-k8s-ctl/pkg/api.(*ApplicationAPI).createLoadBalancer() Creating loadbalancer...                     
> FATA[0003]github.com/maksim-paskal/hcloud-k8s-ctl/cmd/main.go:70 main.main()                                               error="error in create loadbalancer: no subnet or IP available for the given network (service_error)"

**Comment by maksim-paskal** [comment]
I need more context, can you share your `config.yaml` and what the version `hcloud-k8s-ctl -version` ?

**Comment by ramses3** [comment]
Hello,  the version is 0.1.7-c5e8ea3-1675434342

And the yaml

> clusterName: k8s
kubeConfigPath: ~/.kube/hcloud
hetznerToken: 
  main: <token_here>
ipRange: 10.0.0.0/16
sshPrivateKey: ~/.ssh/cluster_rsa
sshPublicKey: ~/.ssh/cluster_rsa.pub
masterCount: 3
networkZone: us-east
location: fsn1
datacenter: fsn1-dc14
masterServers:
  namepattern: master-%d
  servertype: cpx21
  image: ubuntu-20.04
  labels:
    role: master
  waittimeinretry: 3s
  retrytimelimit: 20
  serversinitparams:
    targz: https://github.com/maksim-paskal/hcloud-k8s-ctl/archive/refs/heads/main.tar.gz
    folder: hcloud-k8s-ctl-main
masterLoadBalancer:
  loadbalancertype: lb11
  listenport: 6443
  destinationport: 6443
#cliArgs:
#  loglevel: INFO
#  configpath: config.yaml
#  action: create
deployments: {}
autoscaler:
  enabled: true
  args:
    - --v=4
    - --cloud-provider=hetzner
    - --stderrthreshold=info
    - --expander=least-waste
    - --scale-down-enabled=true
    - --skip-nodes-with-local-storage=false
    - --skip-nodes-with-system-pods=false
    - --scale-down-utilization-threshold=0.8
  defaults:
    min: 0
    max: 20
  workers:
    - location: fsn1
      min: 1
      max: 20
      type:
        #- cx21
        #- cpx21
        #- cx31
        #- cpx31
        #- cx41
        #- cpx41
        #- cx51
        - cpx51
    - location: nbg1
      min: 0
      max: 20
      type:
        #- cx21
        #- cpx21
        #- cx31
        #- cpx31
        #- cx41
        #- cpx41
        #- cx51
        - cpx51
    - location: hel1
      min: 0
      max: 20
      type:
        #- cx21
        #- cpx21
        #- cx31
        #- cpx31
        #- cx41
        #- cpx41
        #- cx51
        - cpx51

**Comment by maksim-paskal** [comment]
@ramses3 Thanks for raising this issue.

Loadbalancer can be created because you select US networkzone, but datacenters for loadbalancer in europe, it's forbidden by the Hetzner Cloud.

To create cluster in US region at Hetzner - you must switch all your config to US location. To fix your problem:
1. please update `hcloud-k8s-ctl` to [latest](https://github.com/maksim-paskal/hcloud-k8s-ctl/releases/tag/v0.1.8) version `0.1.8-763143a-1675439414` when I test your configuration there some critical bugs it your version, please update
2. switch all your `config.yaml` to US region

minimal configuration in `config.yaml` to create high availability cluster in US with autoscaling:
```yaml
ipRange: "10.0.0.0/16"
masterCount: 3
networkZone: us-east
location: ash
datacenter: ash-dc1
masterServers:
  servertype: cpx21
autoscaler:
  workers:
  - location: ash
    type:
    - cpx51
```
